// Данные меню Тот Ещё Гусь
const menuData = {
  "drinks": [
    {
      "name": "Лимонад Цитрусовый 300мл",
      "slug": "limonad-tsitrusovyy-300ml",
      "description": "Освежающий прохладительный напиток с ярким кисло-сладким вкусом цитрусовых фруктов. Подаётся охлаждённым, идеально утоляет жажду",
      "price": "390",
      "calories": "~45 ккал",
      "time": "2 ч",
      "origin": "Франция",
      "history": "Изобретен в Париже XVII в. Цедра мацерируется в сиропе.",
      "facts": "• Без красителей\n• Подается со льдом\n• Идеально утоляет жажду",
      "wine": "-",
      "image": "https://totgoose.github.io/limonad-tsitrusovyy-300ml.jpg",
      "allergens": "Нет",
      "method": "Настаивание + Охлаждение",
      "url": "dishes/limonad-tsitrusovyy-300ml.html"
    },
    {
      "name": "Натуральный ягодный морс",
      "slug": "naturalnyy-yagodnyy-mors",
      "description": "Малина, клубника, чёрная смородина",
      "price": "390",
      "calories": "~60 ккал",
      "time": "30 мин",
      "origin": "Россия",
      "history": "Древнерусский напиток. Ягоды не варят, а мнут.",
      "facts": "• Сохраняет витамин С\n• Малина, клубника, смородина\n• Без консервантов",
      "wine": "-",
      "image": "https://totgoose.github.io/naturalnyy-yagodnyy-mors.jpg",
      "allergens": "Нет",
      "method": "Отжим + Настаивание",
      "url": "dishes/naturalnyy-yagodnyy-mors.html"
    },
    {
      "name": "Вода «Sairme» 0,5л",
      "slug": "voda-sairme-0-5l",
      "description": "Без газа / с газом",
      "price": "300",
      "calories": "0 ккал",
      "time": "-",
      "origin": "Грузия",
      "history": "Грузинская минералка. Бальнеологический курорт.",
      "facts": "• Лечебные свойства\n• Газ/без газа\n• Природная чистота",
      "wine": "-",
      "image": "https://totgoose.github.io/voda-sairme-05l.jpg",
      "allergens": "Нет",
      "method": "Розлив",
      "url": "dishes/voda-sairme-0-5l.html"
    },
    {
      "name": "Черный",
      "slug": "chernyy",
      "description": "Классический крепкий чай с насыщенным вкусом и ароматом",
      "price": "450",
      "calories": "~2-5 ккал",
      "time": "5 мин",
      "origin": "Китай/Тайвань/Индия",
      "history": "Традиции Китая/Индии. 900мл рассчитан на компанию.",
      "facts": "• Заваривается в чайнике\n• Температура 85-100°C\n• Повторное заваривание до 3 раз",
      "wine": "-",
      "image": "https://totgoose.github.io/chernyy.jpg",
      "allergens": "Нет",
      "method": "Заваривание",
      "url": "dishes/chernyy.html"
    },
    {
      "name": "Зеленый сенча",
      "slug": "zelenyy-sencha",
      "description": "Японский зелёный чай с травянистым вкусом и лёгкой терпкостью",
      "price": "450",
      "calories": "~2-5 ккал",
      "time": "5 мин",
      "origin": "Китай/Тайвань/Индия",
      "history": "Традиции Китая/Индии. 900мл рассчитан на компанию.",
      "facts": "• Заваривается в чайнике\n• Температура 85-100°C\n• Повторное заваривание до 3 раз",
      "wine": "-",
      "image": "https://totgoose.github.io/zelenyy-sencha.jpg",
      "allergens": "Нет",
      "method": "Заваривание",
      "url": "dishes/zelenyy-sencha.html"
    },
    {
      "name": "Зеленый с жасмином",
      "slug": "zelenyy-s-zhasminom",
      "description": "Нежный зелёный чай с цветочным ароматом жасмина",
      "price": "450",
      "calories": "~2-5 ккал",
      "time": "5 мин",
      "origin": "Китай/Тайвань/Индия",
      "history": "Традиции Китая/Индии. 900мл рассчитан на компанию.",
      "facts": "• Заваривается в чайнике\n• Температура 85-100°C\n• Повторное заваривание до 3 раз",
      "wine": "-",
      "image": "https://totgoose.github.io/zelenyy-s-zhasminom.jpg",
      "allergens": "Нет",
      "method": "Заваривание",
      "url": "dishes/zelenyy-s-zhasminom.html"
    },
    {
      "name": "Молочный улун",
      "slug": "molochnyy-ulun",
      "description": "Полуферментированный тайваньский чай с кремовым послевкусием",
      "price": "450",
      "calories": "~2-5 ккал",
      "time": "5 мин",
      "origin": "Китай/Тайвань/Индия",
      "history": "Традиции Китая/Индии. 900мл рассчитан на компанию.",
      "facts": "• Заваривается в чайнике\n• Температура 85-100°C\n• Повторное заваривание до 3 раз",
      "wine": "-",
      "image": "https://totgoose.github.io/molochnyy-ulun.jpg",
      "allergens": "Нет",
      "method": "Заваривание",
      "url": "dishes/molochnyy-ulun.html"
    },
    {
      "name": "Бергамот",
      "slug": "bergamot",
      "description": "Чёрный чай с цитрусовой ноткой бергамота (Эрл Грей)",
      "price": "450",
      "calories": "~2-5 ккал",
      "time": "5 мин",
      "origin": "Китай/Тайвань/Индия",
      "history": "Традиции Китая/Индии. 900мл рассчитан на компанию.",
      "facts": "• Заваривается в чайнике\n• Температура 85-100°C\n• Повторное заваривание до 3 раз",
      "wine": "-",
      "image": "https://totgoose.github.io/bergamot.jpg",
      "allergens": "Нет",
      "method": "Заваривание",
      "url": "dishes/bergamot.html"
    },
    {
      "name": "Травяной",
      "slug": "travyanoy",
      "description": "Сбор из лекарственных трав без кофеина",
      "price": "450",
      "calories": "~2-5 ккал",
      "time": "5 мин",
      "origin": "Китай/Тайвань/Индия",
      "history": "Традиции Китая/Индии. 900мл рассчитан на компанию.",
      "facts": "• Заваривается в чайнике\n• Температура 85-100°C\n• Повторное заваривание до 3 раз",
      "wine": "-",
      "image": "https://totgoose.github.io/travyanoy.jpg",
      "allergens": "Нет",
      "method": "Заваривание",
      "url": "dishes/travyanoy.html"
    },
    {
      "name": "Клюквенный",
      "slug": "klyukvennyy",
      "description": "Ягодный чай с кисло-сладким вкусом клюквы",
      "price": "950",
      "calories": "~2-5 ккал",
      "time": "5 мин",
      "origin": "Китай/Тайвань/Индия",
      "history": "Традиции Китая/Индии. 900мл рассчитан на компанию.",
      "facts": "• Заваривается в чайнике\n• Температура 85-100°C\n• Повторное заваривание до 3 раз",
      "wine": "-",
      "image": "https://totgoose.github.io/klyukvennyy.jpg",
      "allergens": "Нет",
      "method": "Заваривание",
      "url": "dishes/klyukvennyy.html"
    },
    {
      "name": "Американо, эспрессо",
      "slug": "amerikano-espresso",
      "description": "Arabica",
      "price": "250",
      "calories": "~5-150 ккал",
      "time": "2 мин",
      "origin": "Италия/Эфиопия",
      "history": "Эфиопское происхождение. Arabica 100%.",
      "facts": "• Давление 9 бар\n• Помол средний/мелкий\n• Молоко any milk",
      "wine": "-",
      "image": "https://totgoose.github.io/amerikano-espresso.jpg",
      "allergens": "Нет/Молочные",
      "method": "Эспрессо-машина",
      "url": "dishes/amerikano-espresso.html"
    },
    {
      "name": "Капучино, двойной эспрессо",
      "slug": "kapuchino-dvoynoy-espresso",
      "description": "Arabica  + Any Milk",
      "price": "450",
      "calories": "~5-150 ккал",
      "time": "2 мин",
      "origin": "Италия/Эфиопия",
      "history": "Эфиопское происхождение. Arabica 100%.",
      "facts": "• Давление 9 бар\n• Помол средний/мелкий\n• Молоко any milk",
      "wine": "-",
      "image": "https://totgoose.github.io/kapuchino-dvoynoy-espresso.jpg",
      "allergens": "Нет/Молочные",
      "method": "Эспрессо-машина",
      "url": "dishes/kapuchino-dvoynoy-espresso.html"
    },
    {
      "name": "Латте",
      "slug": "latte",
      "description": "Arabica  + Any Milk",
      "price": "550",
      "calories": "~5-150 ккал",
      "time": "2 мин",
      "origin": "Италия/Эфиопия",
      "history": "Эфиопское происхождение. Arabica 100%.",
      "facts": "• Давление 9 бар\n• Помол средний/мелкий\n• Молоко any milk",
      "wine": "-",
      "image": "https://totgoose.github.io/latte.jpg",
      "allergens": "Нет/Молочные",
      "method": "Эспрессо-машина",
      "url": "dishes/latte.html"
    }
  ],
  "hot": [
    {
      "name": "Оссобуко",
      "slug": "ossobuko",
      "description": "Стейк из поперечного разреза говяжьей голени с мозговой косточкой, приготовленный на низкой температуре. Подаётся с соусом и гарниром из жаренного фенхеля",
      "price": "2200",
      "calories": "~380 ккал",
      "time": "3 ч",
      "origin": "Италия, Ломбардия",
      "history": "Блюдо Ломбардии XIX в. Название переводится как «полая кость». Первый задокументированный рецепт у П. Артузи.",
      "facts": "• Изначально крестьянская еда\n• Классика подаётся с гремолатой\n• Версия in bianco готовится без томатов",
      "wine": "Бароло, Кьянти Классико",
      "image": "https://totgoose.github.io/ossobuko.jpg",
      "allergens": "Глютен",
      "method": "Бразирование (тушение)",
      "url": "dishes/ossobuko.html"
    },
    {
      "name": "Шея ягнёнка",
      "slug": "sheya-yagnyonka",
      "description": "Томлённая на низкой температуре с солодовым соусом и бренди. Подаётся с жареным луком порей и бейби-картофелем (на двоих)",
      "price": "3900",
      "calories": "~520 ккал",
      "time": "8 ч",
      "origin": "Французская кухня",
      "history": "Традиционное праздничное блюдо. Длительное томление превращает соединительные ткани в нежный желеобразный бульон.",
      "facts": "• Самый сочный отруб ягнёнка\n• 6-8 часов при низкой температуре\n• Идеально делится на двоих",
      "wine": "Шато Неф-дю-Пап, Сира",
      "image": "https://totgoose.github.io/sheya-yagnyonka.jpg",
      "allergens": "Нет",
      "method": "Су-вид / Томление",
      "url": "dishes/sheya-yagnyonka.html"
    },
    {
      "name": "Вымя гриль",
      "slug": "vymya-gril",
      "description": "Жареное говяжье вымя с перечным соусом и цветной капустой",
      "price": "1450",
      "calories": "~280 ккал",
      "time": "1.5 ч",
      "origin": "Восточная Европа",
      "history": "Субпродукт, популярный в восточноевропейской и кавказской кухне. Богат коллагеном и железом.",
      "facts": "• Требует тщательной предварительной очистки\n• На гриле приобретает ореховый вкус\n• Отличная текстура при правильной жарке",
      "wine": "Пино Нуар, Цвайгельт",
      "image": "https://totgoose.github.io/vymya-gril.jpg",
      "allergens": "Нет",
      "method": "Гриль",
      "url": "dishes/vymya-gril.html"
    },
    {
      "name": "Язык молочного теленка",
      "slug": "yazyk-molochnogo-telenka",
      "description": "Глазированный язык теленка с опаленным романо и луком-конфи",
      "price": "990",
      "calories": "~220 ккал",
      "time": "2.5 ч",
      "origin": "Франция",
      "history": "Деликатес французской классики. Язык молочного телёнка считается самым нежным.",
      "facts": "• Снимается кожа сразу после варки\n• Глазировка создаёт карамельную корочку\n• Подаётся с овощами конфи",
      "wine": "Божоле, Гаме",
      "image": "https://totgoose.github.io/yazyk-molochnogo-telenka.jpg",
      "allergens": "Нет",
      "method": "Томление + Глазировка",
      "url": "dishes/yazyk-molochnogo-telenka.html"
    },
    {
      "name": "Кот дю Бёф",
      "slug": "kot-dyu-byof",
      "description": "Говяжий антрекот на кости с томатным чимичури и печёным чесноком (на двоих)",
      "price": "3950",
      "calories": "~650 ккал",
      "time": "40 мин",
      "origin": "Франция",
      "history": "Французский стейк на кости. Подается на двоих, символизирует щедрость и мастерство гриль-мастера.",
      "facts": "• Вес 730-1000 г\n• Толщина ~6 см\n• Кость усиливает мясной вкус при жарке",
      "wine": "Бордо, Мальбек",
      "image": "https://totgoose.github.io/kot-dyu-byof.jpg",
      "allergens": "Нет",
      "method": "Гриль + Духовка",
      "url": "dishes/kot-dyu-byof.html"
    },
    {
      "name": "Телячий желудок со сморчками",
      "slug": "telyachiy-zheludok-so-smorchkami",
      "description": "Желудок, томленный в грибном бульоне, со сморчками в соусе из мадеры",
      "price": "1250",
      "calories": "~190 ккал",
      "time": "3 ч",
      "origin": "Италия/Франция",
      "history": "Итальянское/французское блюдо из субпродуктов. Требует длительного томления для мягкости.",
      "facts": "• Сморчки придают умами-вкус\n• Мадера в соусе балансирует жирность\n• Блюдо для ценителей текстуры",
      "wine": "Кьянти, Санджовезе",
      "image": "https://totgoose.github.io/telyachiy-zheludok-so-smorchkami.jpg",
      "allergens": "Грибы, Сульфиты",
      "method": "Томление",
      "url": "dishes/telyachiy-zheludok-so-smorchkami.html"
    },
    {
      "name": "Почки ягненка в хересе",
      "slug": "pochki-yagnenka-v-herese",
      "description": "Почки в хересе Pedro Ximenez и солодовом соусе со спагетти из цуккини",
      "price": "950",
      "calories": "~210 ккал",
      "time": "30 мин",
      "origin": "Великобритания/Франция",
      "history": "Классика британской и французской кухни. Херес Pedro Ximenez убирает специфический запах.",
      "facts": "• Готовятся строго Medium Rare\n• Херес даёт карамельную сладость\n• Цуккини спагетти добавляют свежесть",
      "wine": "Херес Амонтильядо, Олоросо",
      "image": "https://totgoose.github.io/pochki-yagnenka-v-kherese.jpg",
      "allergens": "Сульфиты",
      "method": "Жарка + Деглазировка",
      "url": "dishes/pochki-yagnenka-v-herese.html"
    },
    {
      "name": "Кости",
      "slug": "kosti",
      "description": "«Сахарная» мозговая говяжья кость, запечённая с розмарином и чесноком",
      "price": "1750",
      "calories": "~350 ккал",
      "time": "45 мин",
      "origin": "Франция",
      "history": "Закуска из мозговых говяжьих костей. Популярна в французских бистро и испанских тавернах.",
      "facts": "• Мозг богат омега-3 и фосфолипидами\n• Запекается разрезом вверх\n• Розмарин и чеснок пробивают жирность",
      "wine": "Мальбек, Шираз",
      "image": "https://totgoose.github.io/kosti.jpg",
      "allergens": "Нет",
      "method": "Запекание",
      "url": "dishes/kosti.html"
    },
    {
      "name": "Бараньи яйца с соусом Субиз",
      "slug": "barani-yaytsa-s-sousom-subiz",
      "description": "Семенники ягненка, жареные с розмарином и чесноком, с соусом Субиз и петрушкой-фри",
      "price": "980",
      "calories": "~240 ккал",
      "time": "25 мин",
      "origin": "Средиземноморье",
      "history": "Средиземноморский деликатес. Соус Субиз на основе лука и бешамеля сглаживает вкус.",
      "facts": "• Петрушка-фри даёт хруст\n• Соус готовится 40 минут на сливочном масле\n• Редкое, но традиционное блюдо",
      "wine": "Гренаш, Темпранильо",
      "image": "https://totgoose.github.io/barani-yaytsa-s-sousom-subiz.jpg",
      "allergens": "Глютен, Молочные",
      "method": "Жарка + Соус",
      "url": "dishes/barani-yaytsa-s-sousom-subiz.html"
    },
    {
      "name": "Стейк из говяжьей печени",
      "slug": "steyk-iz-govyazhey-pecheni",
      "description": "Говяжья печень гриль Medium Rare с лимонным луком и медово-горчичным соусом",
      "price": "1350",
      "calories": "~180 ккал",
      "time": "15 мин",
      "origin": "Германия",
      "history": "Популярен в немецкой и русской кухне. Готовится Medium Rare для сохранения нежности.",
      "facts": "• Не требует длительного маринования\n• Лимонный лук убирает металлический привкус\n• Медово-горчичный соус балансирует вкус",
      "wine": "Цвайгельт, Бургундское красное",
      "image": "https://totgoose.github.io/steyk-iz-govyazhey-pecheni.jpg",
      "allergens": "Нет",
      "method": "Гриль / Жарка",
      "url": "dishes/steyk-iz-govyazhey-pecheni.html"
    },
    {
      "name": "Утиная грудка Магре",
      "slug": "utinaya-grudka-magre",
      "description": "Жареная утиная грудка по-французски с бейби морковкой и цитрусовым соусом",
      "price": "1150",
      "calories": "~320 ккал",
      "time": "25 мин",
      "origin": "Франция (Юго-Запад)",
      "history": "Французская классика (Magret de Canard). Жир утки вытапливается при жарке, создавая хрустящую кожу.",
      "facts": "• Грудка мускусной утки\n• Надрезы кожицы помогают вытапливать жир\n• Цитрусовый соус контрастирует с жирностью",
      "wine": "Пино Нуар, Божоле",
      "image": "https://totgoose.github.io/utinaya-grudka-magre.jpg",
      "allergens": "Нет",
      "method": "Жарка",
      "url": "dishes/utinaya-grudka-magre.html"
    },
    {
      "name": "Рябчик",
      "slug": "ryabchik",
      "description": "Целая птичка почти без костей со спагетти из корня сельдерея",
      "price": "1900",
      "calories": "~160 ккал",
      "time": "50 мин",
      "origin": "Россия/Франция",
      "history": "Дичь, любимая русской аристократией XIX в. Почти нет костей, нежное белое мясо.",
      "facts": "• Готовится целой тушкой\n• Сельдерей сохраняет влагу\n• Традиционно подается с брусничным соусом",
      "wine": "Бургундия, Пино Нуар",
      "image": "https://totgoose.github.io/ryabchik.jpg",
      "allergens": "Нет",
      "method": "Запекание",
      "url": "dishes/ryabchik.html"
    }
  ],
  "hotsnacks": [
    {
      "name": "Волован À la bourguignonne",
      "slug": "volovan-à-la-bourguignonne",
      "description": "Корзинка из слоеного теста с бычьими хвостами в Pinot Noir и сливочным соусом из белых грибов",
      "price": "1450",
      "calories": "~340 ккал",
      "time": "1 ч",
      "origin": "Франция",
      "history": "Французская выпечка XVII в. Тесто поднимается в 7 слоев, создавая «корзину».",
      "facts": "• Бычьи хвосты тушатся 6 часов\n• Сливочный соус из белых грибов\n• Подается горячим",
      "wine": "Пино Нуар, Божоле Виллаж",
      "image": "https://totgoose.github.io/volovan-à-la-bourguignonne.jpg",
      "allergens": "Глютен, Молочные, Грибы, Сульфиты",
      "method": "Выпечка + Тушение",
      "url": "dishes/volovan-à-la-bourguignonne.html"
    },
    {
      "name": "Бюш-Де-Шевр",
      "slug": "byush-de-shevr",
      "description": "Жареный козий сыр с плесенью, чатни из хурмы, клубника, инжирная мастарда",
      "price": "960",
      "calories": "~280 ккал",
      "time": "20 мин",
      "origin": "Франция",
      "history": "Французский сырный деликатес. Чатни из хурмы балансирует кислоту плесени.",
      "facts": "• Козий сыр с белой плесенью\n• Хурма карамелизуется\n• Инжирная мастарда даёт сладость",
      "wine": "Совиньон Блан, Сэмийон",
      "image": "https://totgoose.github.io/byush-de-shevr.jpg",
      "allergens": "Молочные (плесень), Фрукты",
      "method": "Запекание",
      "url": "dishes/byush-de-shevr.html"
    },
    {
      "name": "Киш с крабом",
      "slug": "kish-s-krabom",
      "description": "Горячий тарт с морепродуктами и мясом камчатского краба",
      "price": "950",
      "calories": "~310 ккал",
      "time": "45 мин",
      "origin": "Франция (Лотарингия)",
      "history": "Лотарингский пирог. Краб добавляет сладость тесту и яйцам.",
      "facts": "• Основа из песочного теста\n• Заливка на основе яиц и сливок\n• Камчатский краб премиум-класса",
      "wine": "Шардоне, Пино Блан",
      "image": "https://totgoose.github.io/kish-s-krabom.jpg",
      "allergens": "Глютен, Яйца, Молочные, Ракообразные",
      "method": "Выпечка",
      "url": "dishes/kish-s-krabom.html"
    },
    {
      "name": "Стейк из капусты",
      "slug": "steyk-iz-kapusty",
      "description": "Жареная капуста с ароматными травами и копченой сметаной",
      "price": "720",
      "calories": "~180 ккал",
      "time": "25 мин",
      "origin": "Авторская",
      "history": "Вегетарианский тренд 2010-х. Копченая сметана дает мясной вкус.",
      "facts": "• Капуста запекается целиком\n• Травы добавляют аромат\n• Сметана даёт умами",
      "wine": "Гевюрцтраминер, Рислинг",
      "image": "https://totgoose.github.io/steyk-iz-kapusty.jpg",
      "allergens": "Молочные",
      "method": "Обжарка + Запекание",
      "url": "dishes/steyk-iz-kapusty.html"
    },
    {
      "name": "Французский луковый пирог",
      "slug": "frantsuzskiy-lukovyy-pirog",
      "description": "Карамелизированный лук шалот на слоеном тесте",
      "price": "650",
      "calories": "~260 ккал",
      "time": "1 ч",
      "origin": "Франция",
      "history": "Упрощенная версия супа. Лук шалот слаще обычного и быстрее карамелизуется.",
      "facts": "• Лук тушится 30 мин\n• Слоеное тесто хрустит\n• Подается теплым",
      "wine": "Шардоне, Вионье",
      "image": "https://totgoose.github.io/frantsuzskiy-lukovyy-pirog.jpg",
      "allergens": "Глютен, Молочные, Яйца",
      "method": "Карамелизация + Выпечка",
      "url": "dishes/frantsuzskiy-lukovyy-pirog.html"
    },
    {
      "name": "Жареная Фуа-гра",
      "slug": "zharenaya-fua-gra",
      "description": "С фундуком, яблоками в меде и соусом из киви и манго",
      "price": "2400",
      "calories": "~480 ккал",
      "time": "15 мин",
      "origin": "Франция (Эльзас)",
      "history": "Деликатес эльзасской кухни. Сахар/фрукты убирают жирность.",
      "facts": "• Обжаривается 30 сек/сторона\n• Фундук добавляет хруст\n• Соус из киви и манго освежает",
      "wine": "Сотерн, Токай Асу",
      "image": "https://totgoose.github.io/zharenaya-fua-gra.jpg",
      "allergens": "Орехи, Фрукты",
      "method": "Быстрая обжарка",
      "url": "dishes/zharenaya-fua-gra.html"
    }
  ],
  "desserts": [
    {
      "name": "Crème Brûlée",
      "slug": "crème-brûlée",
      "description": "Классический французский сливочный десерт с Фуа-Гра и клубникой",
      "price": "950",
      "calories": "~320 ккал",
      "time": "4 ч (с охлаждением)",
      "origin": "Франция",
      "history": "Франция XVII в. Сахарная корка бьется ложкой.",
      "facts": "• Запекается на водяной бане\n• Фуа-гра в рецепте ресторана\n• Горелка создает корку за 10 сек",
      "wine": "Сотерн, Токай Асу",
      "image": "https://totgoose.github.io/crème-brûlée.jpg",
      "allergens": "Яйца, Молочные",
      "method": "Водяная баня + Горелка",
      "url": "dishes/crème-brûlée.html"
    },
    {
      "name": "Бейлиз мильфей",
      "slug": "beyliz-milfey",
      "description": "Коржи из бездрожжевого теста с бейлиз-кремом и малиновым соусом",
      "price": "790",
      "calories": "~410 ккал",
      "time": "1.5 ч",
      "origin": "Франция",
      "history": "Французский слоеный десерт. Бейлиз дает сливочно-виски вкус.",
      "facts": "• 1000 листов теста\n• Крем на основе ликера\n• Малиновый соус кислит",
      "wine": "Портвейн, Мадера",
      "image": "https://totgoose.github.io/beyliz-milfey.jpg",
      "allergens": "Глютен, Яйца, Молочные, Алкоголь",
      "method": "Выпечка + Сборка",
      "url": "dishes/beyliz-milfey.html"
    },
    {
      "name": "Персиковый тарт с Горгонзолой",
      "slug": "persikovyy-tart-s-gorgonzoloy",
      "description": "Слоёный пирог с персиком в бальзамическом соусе, с ванильным мороженым",
      "price": "760",
      "calories": "~360 ккал",
      "time": "50 мин",
      "origin": "Италия",
      "history": "Итальянский контраст вкусов. Горгонзола плавится с карамелью.",
      "facts": "• Сладкое и соленое\n• Бальзамик уваривается\n• Ванильное мороженое контрастирует",
      "wine": "Ламбруско, Просекко",
      "image": "https://totgoose.github.io/persikovyy-tart-s-gorgonzoloy.jpg",
      "allergens": "Глютен, Молочные (плесень), Яйца",
      "method": "Выпечка",
      "url": "dishes/persikovyy-tart-s-gorgonzoloy.html"
    }
  ],
  "main": [
    {
      "name": "Филе-миньон со сморчками",
      "slug": "file-minon-so-smorchkami",
      "description": "Говяжья вырезка со сморчками в сливочном соусе и жареным цуккини",
      "price": "1850",
      "calories": "~420 ккал",
      "time": "30 мин",
      "origin": "Франция",
      "history": "Классика французской высокой кухни. Сморчки содержат микодотин.",
      "facts": "• Вырезка — самый нежный отруб\n• Сливочный соус связывает вкус\n• Цуккини на гриле добавляют легкость",
      "wine": "Бордо, Каберне Фран",
      "image": "https://totgoose.github.io/file-minon-so-smorchkami.jpg",
      "allergens": "Грибы, Молочные",
      "method": "Обжарка + Тушение",
      "url": "dishes/file-minon-so-smorchkami.html"
    },
    {
      "name": "Бефстроганов из говяжьей вырезки",
      "slug": "befstroganov-iz-govyazhey-vyrezki",
      "description": "В сметано-томатном соусе с коньяком, с пюре из батата и битыми огурцами",
      "price": "1250",
      "calories": "~380 ккал",
      "time": "40 мин",
      "origin": "Россия",
      "history": "Назван в честь графа Строганова. Коньяк обязателен в оригинале.",
      "facts": "• Мясо нарезается поперек волокон\n• Сметано-томатный соус\n• Пюре из батата слаще обычного",
      "wine": "Каберне Совиньон, Шираз",
      "image": "https://totgoose.github.io/befstroganov-iz-govyazhey-vyrezki.jpg",
      "allergens": "Молочные",
      "method": "Обжарка + Тушение",
      "url": "dishes/befstroganov-iz-govyazhey-vyrezki.html"
    },
    {
      "name": "Лосось",
      "slug": "losos",
      "description": "Филе на коже Medium Rare с жареным картофелем и шпинатом",
      "price": "1650",
      "calories": "~310 ккал",
      "time": "20 мин",
      "origin": "Скандинавия",
      "history": "Скандинавская традиция. Кожа защищает мясо от пересушки.",
      "facts": "• Готовится кожей вниз\n• Шпинат вянет от тепла\n• Картофель хрустит",
      "wine": "Пино Гриджио, Альбариньо",
      "image": "https://totgoose.github.io/losos.jpg",
      "allergens": "Рыба",
      "method": "Обжарка на коже",
      "url": "dishes/losos.html"
    },
    {
      "name": "Палтус",
      "slug": "paltus",
      "description": "Филе со сливочно-луковым соусом с Мадерой и пастой фрегола",
      "price": "1650",
      "calories": "~290 ккал",
      "time": "25 мин",
      "origin": "Франция",
      "history": "Северная Атлантика. Мадера дает ореховость.",
      "facts": "• Белое мясо, плотная текстура\n• Паста фрегола впитывает соус\n• Луково-сливочный соус насыщает",
      "wine": "Шардоне, Вионье",
      "image": "https://totgoose.github.io/paltus.jpg",
      "allergens": "Рыба, Молочные, Сульфиты",
      "method": "Жарка + Соус",
      "url": "dishes/paltus.html"
    },
    {
      "name": "Морской гребешок",
      "slug": "morskoy-grebeshok",
      "description": "Жареный с пюре Рамеско Верде и цитрусовой заправкой",
      "price": "2900",
      "calories": "~240 ккал",
      "time": "15 мин",
      "origin": "Франция/Италия",
      "history": "Средиземноморский деликатес. Готовится 2 минуты с каждой стороны.",
      "facts": "• Не переваривается\n• Пюре Рамеско Верде (брокколи)\n• Цитрусовая заправка освежает",
      "wine": "Совиньон Блан, Пикпуль",
      "image": "https://totgoose.github.io/morskoy-grebeshok.jpg",
      "allergens": "Моллюски, Молочные",
      "method": "Быстрая обжарка",
      "url": "dishes/morskoy-grebeshok.html"
    }
  ],
  "lent": [
    {
      "name": "Карпаччо из цветной капусты",
      "slug": "karpachcho-iz-tsvetnoy-kapusty",
      "description": "С трюфельной заправкой, муссом из цветной капусты и миндалем",
      "price": "680",
      "calories": "~120 ккал",
      "time": "15 мин",
      "origin": "Италия",
      "history": "Итальянская техника для овощей. Мандолина дает тонкие слайсы.",
      "facts": "• Трюфельная заправка без сливок\n• Мусс из цветной капусты легкий\n• Миндаль даёт хруст",
      "wine": "Пино Гриджио, Гави",
      "image": "https://totgoose.github.io/karpachcho-iz-tsvetnoy-kapusty.jpg",
      "allergens": "Орехи (миндаль)",
      "method": "Нарезка + Маринование",
      "url": "dishes/karpachcho-iz-tsvetnoy-kapusty.html"
    },
    {
      "name": "Карпаччо из свеклы",
      "slug": "karpachcho-iz-svekly",
      "description": "С соусом «Винегрет», водорослями Нури и кедровыми орешками",
      "price": "620",
      "calories": "~90 ккал",
      "time": "1 ч",
      "origin": "Авторская",
      "history": "Современная русская кухня. Водоросли нори дают морской вкус.",
      "facts": "• Свекла запекается в фольге\n• Соус винегрет классический\n• Кедровые орешки жирные",
      "wine": "Розе, Пино Нуар (легкий)",
      "image": "https://totgoose.github.io/karpachcho-iz-svekly.jpg",
      "allergens": "Орехи",
      "method": "Запекание + Нарезка",
      "url": "dishes/karpachcho-iz-svekly.html"
    },
    {
      "name": "Ливанский хумус",
      "slug": "livanskiy-humus",
      "description": "С маринованным Романо и артишоками",
      "price": "580",
      "calories": "~180 ккал",
      "time": "2 ч",
      "origin": "Ливан",
      "history": "Ближневосточный staple. Нут замачивают на ночь для мягкости.",
      "facts": "• Тахини даёт ореховый вкус\n• Лимон и чеснок балансируют\n• Романо и артишоки добавляют свежесть",
      "wine": "Розе, Безалкогольный мохито",
      "image": "https://totgoose.github.io/livanskiy-khumus-2.jpg",
      "allergens": "Кунжут, Нут",
      "method": "Варка + Блендирование",
      "url": "dishes/livanskiy-humus.html"
    },
    {
      "name": "Большой зеленый салат",
      "slug": "bolshoy-zelenyy-salat",
      "description": "Листья салата, авокадо, горошек, брокколи, цуккини кунжутная заправка",
      "price": "950",
      "calories": "~150 ккал",
      "time": "10 мин",
      "origin": "Авторская",
      "history": "Современный ЗОЖ-тренд. Кунжутная заправка на базе тахини.",
      "facts": "• Брокколи бланшируется 1 мин\n• Авокадо добавляет сливочность\n• Горошек даёт хруст",
      "wine": "Совиньон Блан, Грин Вельтлинер",
      "image": "https://totgoose.github.io/bolshoy-zelenyy-salat-2.jpg",
      "allergens": "Кунжут",
      "method": "Нарезка + Сборка",
      "url": "dishes/bolshoy-zelenyy-salat.html"
    },
    {
      "name": "Суп из чечевицы",
      "slug": "sup-iz-chechevitsy",
      "description": "С карри на кокосовых сливках, лаймом, мятой и кинзой",
      "price": "650",
      "calories": "~180 ккал",
      "time": "40 мин",
      "origin": "Индия/Ближний Восток",
      "history": "Ближневосточная классика. Кокосовое молоко заменяет сливки.",
      "facts": "• Карри даёт пряность\n• Лайм и кинза освежают\n• Постная альтернатива",
      "wine": "Безалкогольный, Рислинг",
      "image": "https://totgoose.github.io/sup-iz-chechevitsy.jpg",
      "allergens": "Нет",
      "method": "Варка",
      "url": "dishes/sup-iz-chechevitsy.html"
    },
    {
      "name": "Картофельный рости с грибами",
      "slug": "kartofelnyy-rosti-s-gribami",
      "description": "Швейцарское блюдо из тертого картофеля с вешенками и постной сметаной",
      "price": "850",
      "calories": "~240 ккал",
      "time": "30 мин",
      "origin": "Швейцария",
      "history": "Швейцарское блюдо. Картофель трется на крупной терке.",
      "facts": "• Выжимается вся влага\n• Вешенки тушатся отдельно\n• Постная сметана",
      "wine": "Пино Нуар, Гаме",
      "image": "https://totgoose.github.io/kartofelnyy-rosti-s-gribami.jpg",
      "allergens": "Грибы",
      "method": "Обжарка",
      "url": "dishes/kartofelnyy-rosti-s-gribami.html"
    },
    {
      "name": "Стейк из капусты",
      "slug": "steyk-iz-kapusty",
      "description": "Жареная капуста с травами и постной сметаной",
      "price": "620",
      "calories": "~180 ккал",
      "time": "25 мин",
      "origin": "Авторская",
      "history": "Вегетарианский тренд 2010-х. Копченая сметана дает мясной вкус.",
      "facts": "• Капуста запекается целиком\n• Травы добавляют аромат\n• Сметана даёт умами",
      "wine": "Гевюрцтраминер, Рислинг",
      "image": "https://totgoose.github.io/steyk-iz-kapusty-2.jpg",
      "allergens": "Молочные",
      "method": "Обжарка + Запекание",
      "url": "dishes/steyk-iz-kapusty.html"
    },
    {
      "name": "Фетучини с белыми грибами",
      "slug": "fetuchini-s-belymi-gribami",
      "description": "Соус из уваренных белых грибов и оливкового масла",
      "price": "990",
      "calories": "~380 ккал",
      "time": "25 мин",
      "origin": "Италия",
      "history": "Итальянская паста. Белые грибы сушат для концентрации.",
      "facts": "• Тесто из твердых сортов\n• Оливковое масло Extra Virgin\n• Уваренный бульон грибов",
      "wine": "Кьянти, Санджовезе",
      "image": "https://totgoose.github.io/fetuchini-s-belymi-gribami.jpg",
      "allergens": "Глютен, Грибы",
      "method": "Варка + Соус",
      "url": "dishes/fetuchini-s-belymi-gribami.html"
    },
    {
      "name": "Пшённая каша",
      "slug": "pshyonnaya-kasha",
      "description": "С мускатной тыквой и вялеными томатами",
      "price": "690",
      "calories": "~150 ккал",
      "time": "30 мин",
      "origin": "Россия",
      "history": "Славянская традиция. Тыква добавляет карамельность.",
      "facts": "• Крупа промывается до чистой воды\n• Тыква запекается отдельно\n• Вяленые томаты дают кислинку",
      "wine": "Безалкогольный",
      "image": "https://totgoose.github.io/pshyonnaya-kasha.jpg",
      "allergens": "Нет",
      "method": "Варка + Запекание",
      "url": "dishes/pshyonnaya-kasha.html"
    },
    {
      "name": "Сладкая тыква",
      "slug": "sladkaya-tykva",
      "description": "Запеченная тыква с соусом Маракуйя и карамелизированным пеканом",
      "price": "750",
      "calories": "~180 ккал",
      "time": "45 мин",
      "origin": "Авторская",
      "history": "Осенний десерт. Пекан карамелизуется в духовке.",
      "facts": "• Маракуйя даёт тропическую кислинку\n• Тыква выбирается мускатная\n• Запекается с корицей",
      "wine": "Мускат, Сотерн (десертный)",
      "image": "https://totgoose.github.io/sladkaya-tykva.jpg",
      "allergens": "Орехи",
      "method": "Запекание",
      "url": "dishes/sladkaya-tykva.html"
    }
  ],
  "soups": [
    {
      "name": "Французский луковый суп (запеченный)",
      "slug": "frantsuzskiy-lukovyy-sup-zapechennyy",
      "description": "По классическому лионскому рецепту",
      "price": "650",
      "calories": "~290 ккал",
      "time": "1 ч",
      "origin": "Франция",
      "history": "Парижские рынки XVIII в. Гренки с грюйером — ключ к блюду.",
      "facts": "• Лук карамелизуется 40 мин\n• Грюйер тянется\n• Подается в глиняных мисках",
      "wine": "Совиньон Блан, Мюскаде",
      "image": "https://totgoose.github.io/frantsuzskiy-lukovyy-sup-zapechennyy.jpg",
      "allergens": "Глютен, Молочные",
      "method": "Карамелизация + Гратинирование",
      "url": "dishes/frantsuzskiy-lukovyy-sup-zapechennyy.html"
    },
    {
      "name": "Марсельский суп",
      "slug": "marselskiy-sup",
      "description": "Томатный суп с фенхелем, кальмарами, мидиями, лососем, палтусом и креветками",
      "price": "1250",
      "calories": "~220 ккал",
      "time": "40 мин",
      "origin": "Франция (Марсель)",
      "history": "Прованская уха (Bouillabaisse). Варится из 5 видов рыбы минимум.",
      "facts": "• Рыба закладывается поэтапно\n• Фенхель даёт анисовый вкус\n• Подается с руйем",
      "wine": "Розе Прованс, Верментино",
      "image": "https://totgoose.github.io/marselskiy-sup.jpg",
      "allergens": "Рыба, Моллюски, Ракообразные",
      "method": "Варка",
      "url": "dishes/marselskiy-sup.html"
    }
  ],
  "raw": [
    {
      "name": "Тартар из говяжьей вырезки",
      "slug": "tartar-iz-govyazhey-vyrezki",
      "description": "С мостардой и эспуме из сыра Грано Падано",
      "price": "980",
      "calories": "~290 ккал",
      "time": "15 мин",
      "origin": "Франция",
      "history": "Парижские бистро 1920-х. Рубится только ножом, никогда мясорубкой.",
      "facts": "• Мостарда даёт пикантность\n• Эспуме из Грано Падано связывает\n• Подается сразу после нарезки",
      "wine": "Пино Нуар, Божоле",
      "image": "https://totgoose.github.io/tartar-iz-govyazhey-vyrezki.jpg",
      "allergens": "Яйца, Молочные, Горчица",
      "method": "Рубка + Сборка",
      "url": "dishes/tartar-iz-govyazhey-vyrezki.html"
    },
    {
      "name": "Севиче из морского гребешка",
      "slug": "seviche-iz-morskogo-grebeshka",
      "description": "Сахалинский гребешок с огурцом, соком юдзу, фенхелем и виноградом",
      "price": "1850",
      "calories": "~160 ккал",
      "time": "15 мин",
      "origin": "Перу",
      "history": "Перуанское наследие. Лайм «готовит» рыбу денатурацией белка.",
      "facts": "• Маринуется 5-7 минут\n• Юдзу даёт цитрусовую кислинку\n• Фенхель и виноград добавляют текстуру",
      "wine": "Альбариньо, Вердиккьо",
      "image": "https://totgoose.github.io/seviche-iz-morskogo-grebeshka.jpg",
      "allergens": "Моллюски, Цитрусовые",
      "method": "Маринование",
      "url": "dishes/seviche-iz-morskogo-grebeshka.html"
    },
    {
      "name": "Тартар из лосося",
      "slug": "tartar-iz-lososya",
      "description": "С заправкой из Саке и эспуме из Биска",
      "price": "1350",
      "calories": "~220 ккал",
      "time": "15 мин",
      "origin": "Япония/Скандинавия",
      "history": "Скандинавско-японский фьюжн. Саке усиливает умами и убирает рыбный запах.",
      "facts": "• Лосось замораживается -20°C 24ч\n• Бисковый эспуме даёт насыщенность\n• Заправка из саке и имбиря",
      "wine": "Рислинг, Гевюрцтраминер",
      "image": "https://totgoose.github.io/tartar-iz-lososya.jpg",
      "allergens": "Рыба, Яйца, Соя",
      "method": "Нарезка + Сборка",
      "url": "dishes/tartar-iz-lososya.html"
    }
  ],
  "tapas": [
    {
      "name": "Крекер с анчоусом и цуккини с мягким сыром",
      "slug": "kreker-s-anchousom-i-tsukkini-s-myagkim-syrom",
      "description": " Хрустящий крекер с солёной рыбой, свежими кабачками и нежным сыром ",
      "price": "140",
      "calories": "~120 ккал",
      "time": "10 мин",
      "origin": "Испания",
      "history": "Испанские тапас. Анчоусы из Кантабрии считаются лучшими в мире.",
      "facts": "• Анчоусы солят и выдерживают 8-10 мес\n• Цуккини маринуют в лимоне\n• Крекер заменяет хлеб для хруста",
      "wine": "Альбариньо, Верментино",
      "image": "https://totgoose.github.io/kreker-s-anchousom-i-tsukkini-s-myagkim-syrom.jpg",
      "allergens": "Рыба, Молочные, Глютен",
      "method": "Сборка",
      "url": "dishes/kreker-s-anchousom-i-tsukkini-s-myagkim-syrom.html"
    },
    {
      "name": "Крекер с сырным муссом из палтуса и тунца и щучьей икрой",
      "slug": "kreker-s-syrnym-mussom-iz-paltusa-i-tuntsa-i-schuchey-ikroy",
      "description": "Хрустящая основа с воздушным рыбным кремом и красной икрой",
      "price": "140",
      "calories": "~140 ккал",
      "time": "15 мин",
      "origin": "Авторская",
      "history": "Современная интерпретация канапе. Мусс стабилизируется желатином для формы.",
      "facts": "• Мусс готовится на базе рыбного бульона\n• Щучья икра добавляет солоноватость\n• Воздушная текстура достигается блендером",
      "wine": "Совиньон Блан, Рислинг",
      "image": "https://totgoose.github.io/kreker-s-syrnym-mussom-iz-paltusa-i-tuntsa-i-shchuchey-ikroy.jpg",
      "allergens": "Рыба, Молочные, Глютен",
      "method": "Сборка",
      "url": "dishes/kreker-s-syrnym-mussom-iz-paltusa-i-tuntsa-i-schuchey-ikroy.html"
    },
    {
      "name": "Брускетта луком конфи и мягким сыром",
      "slug": "brusketta-lukom-konfi-i-myagkim-syrom",
      "description": "Поджаренный багет с карамелизированным луком и сливочным сыром ",
      "price": "420",
      "calories": "~220 ккал",
      "time": "20 мин",
      "origin": "Италия",
      "history": "Итальянская уличная еда. Конфи готовили часами на медленном огне.",
      "facts": "• Лук томится в масле при 90°C\n• Багет поджаривается с чесноком\n• Сыр растапливается от тепла лука",
      "wine": "Пино Гриджио, Кортезе",
      "image": "https://totgoose.github.io/brusketta-lukom-konfi-i-myagkim-syrom.jpg",
      "allergens": "Глютен, Молочные",
      "method": "Томление + Сборка",
      "url": "dishes/brusketta-lukom-konfi-i-myagkim-syrom.html"
    },
    {
      "name": "Брускетта с опалённым тунцом",
      "slug": "brusketta-s-opalyonnym-tuntsom",
      "description": "Тост с слегка обжаренным свежим тунцом   ",
      "price": "680",
      "calories": "~280 ккал",
      "time": "15 мин",
      "origin": "Италия/Япония",
      "history": "Японско-итальянский фьюжн. Тунец обжаривается секундами только снаружи.",
      "facts": "• Внутри остаётся сырым\n• Кунжутная панировка даёт ореховость\n• Подается сразу после обжарки",
      "wine": "Розе Прованс, Гевюрцтраминер",
      "image": "https://totgoose.github.io/brusketta-s-opalyonnym-tuntsom.jpg",
      "allergens": "Рыба, Глютен, Кунжут",
      "method": "Обжарка + Сборка",
      "url": "dishes/brusketta-s-opalyonnym-tuntsom.html"
    },
    {
      "name": "Брускетта с гусем",
      "slug": "brusketta-s-gusem",
      "description": "Томленный в хересе гусь, вяленые томаты, апельсиновый конфитюр на бриошь",
      "price": "890",
      "calories": "~350 ккал",
      "time": "4 ч",
      "origin": "Франция",
      "history": "Французская закуска. Гусь томлен в хересе 4 часа для максимальной нежности.",
      "facts": "• Вяленые томаты дают умами\n• Апельсиновый конфитюр балансирует жир\n• Бриошь подслащает подачу",
      "wine": "Рислинг, Пино Блан",
      "image": "https://totgoose.github.io/brusketta-s-gusem.jpg",
      "allergens": "Глютен, Молочные, Сульфиты",
      "method": "Томление + Сборка",
      "url": "dishes/brusketta-s-gusem.html"
    },
    {
      "name": "Утиные «суси» (4 шт.)",
      "slug": "utinye-susi-4-sht",
      "description": "Тонкие слайсы 12-дневной вяленой утиной грудки на сушеной черной сливе",
      "price": "590",
      "calories": "~210 ккал",
      "time": "14 д",
      "origin": "Авторская",
      "history": "Авторская игра с формой. 12-дневная вяленая грудка концентрирует вкус.",
      "facts": "• Вяление убирает влагу\n• Черная слива даёт кислинку\n• Форма напоминает японские роллы",
      "wine": "Гевюрцтраминер, Мускат",
      "image": "https://totgoose.github.io/utinye-susi-4-sht.jpg",
      "allergens": "Нет",
      "method": "Вяление + Сборка",
      "url": "dishes/utinye-susi-4-sht.html"
    }
  ],
  "cold": [
    {
      "name": "Пате из утиной печени с Фуа-гра",
      "slug": "pate-iz-utinoy-pecheni-s-fua-gra",
      "description": "С луком конфи, томлёном в утином жиру",
      "price": "950",
      "calories": "~410 ккал",
      "time": "2 ч",
      "origin": "Франция",
      "history": "Французский рустик. Конфи сохраняет влагу и аромат печени.",
      "facts": "• Томится в собственном жиру\n• Лук конфи даёт сладость\n• Подается охлажденным 2-3 дня",
      "wine": "Сотерн, Токай",
      "image": "https://totgoose.github.io/pate-iz-utinoy-pecheni-s-fua-gra.jpg",
      "allergens": "Нет",
      "method": "Запекание + Томление",
      "url": "dishes/pate-iz-utinoy-pecheni-s-fua-gra.html"
    },
    {
      "name": "Паштет из говяжьей печени",
      "slug": "pashtet-iz-govyazhey-pecheni",
      "description": "Со сливочным эспуме из белых грибов",
      "price": "560",
      "calories": "~280 ккал",
      "time": "1 ч",
      "origin": "Россия",
      "history": "Русская классика. Эспуме из белых грибов дает воздушную текстуру.",
      "facts": "• Печень не переваривается\n• Сифон создает пену\n• Подается с гренками",
      "wine": "Мерло, Гаме",
      "image": "https://totgoose.github.io/pashtet-iz-govyazhey-pecheni.jpg",
      "allergens": "Молочные, Грибы",
      "method": "Блендирование + Сифон",
      "url": "dishes/pashtet-iz-govyazhey-pecheni.html"
    },
    {
      "name": "Риет из атлантической скумбрии",
      "slug": "riet-iz-atlanticheskoy-skumbrii",
      "description": "С домашней Рикоттой, Тепенаде, щучьей икрой и тостами из Бриошь",
      "price": "860",
      "calories": "~320 ккал",
      "time": "3 ч",
      "origin": "Франция (Бретань)",
      "history": "Бретонская техника консервации. Изначально риет делали из свинины.",
      "facts": "• Рыба томится в жиру 3 часа\n• Тепенаде из маслин даёт горчинку\n• Домашняя рикотта смягчает вкус",
      "wine": "Мюскаде, Пикпуль",
      "image": "https://totgoose.github.io/riet-iz-atlanticheskoy-skumbrii.jpg",
      "allergens": "Рыба, Молочные, Глютен",
      "method": "Томление в жиру",
      "url": "dishes/riet-iz-atlanticheskoy-skumbrii.html"
    },
    {
      "name": "Ливанский хумус",
      "slug": "livanskiy-humus",
      "description": "С маринованным Романо и артишоками",
      "price": "580",
      "calories": "~180 ккал",
      "time": "2 ч",
      "origin": "Ливан",
      "history": "Ближневосточный staple. Нут замачивают на ночь для мягкости.",
      "facts": "• Тахини даёт ореховый вкус\n• Лимон и чеснок балансируют\n• Романо и артишоки добавляют свежесть",
      "wine": "Розе, Безалкогольный мохито",
      "image": "https://totgoose.github.io/livanskiy-khumus.jpg",
      "allergens": "Кунжут, Нут",
      "method": "Варка + Блендирование",
      "url": "dishes/livanskiy-humus.html"
    },
    {
      "name": "Салат с крабом",
      "slug": "salat-s-krabom",
      "description": "Филе 1-й фаланги краба с чатни из манго, клубникой и лимонно-сливочным эспуме",
      "price": "1750",
      "calories": "~240 ккал",
      "time": "20 мин",
      "origin": "Авторская",
      "history": "Люксовая закуска. 1-я фаланга краба — самое нежное мясо.",
      "facts": "• Чатни из манго даёт сладость\n• Клубника добавляет кислинку\n• Лимонно-сливочный эспуме связывает вкус",
      "wine": "Шардоне, Совиньон Блан",
      "image": "https://totgoose.github.io/salat-s-krabom.jpg",
      "allergens": "Ракообразные, Молочные",
      "method": "Сборка",
      "url": "dishes/salat-s-krabom.html"
    },
    {
      "name": "Большой зеленый салат",
      "slug": "bolshoy-zelenyy-salat",
      "description": "Листья салата, авокадо, молодой стручковый горошек, брокколи, цуккини кунжутная заправка",
      "price": "950",
      "calories": "~150 ккал",
      "time": "10 мин",
      "origin": "Авторская",
      "history": "Современный ЗОЖ-тренд. Кунжутная заправка на базе тахини.",
      "facts": "• Брокколи бланшируется 1 мин\n• Авокадо добавляет сливочность\n• Горошек даёт хруст",
      "wine": "Совиньон Блан, Грин Вельтлинер",
      "image": "https://totgoose.github.io/bolshoy-zelenyy-salat.jpg",
      "allergens": "Кунжут",
      "method": "Нарезка + Сборка",
      "url": "dishes/bolshoy-zelenyy-salat.html"
    },
    {
      "name": "Pâté en croute",
      "slug": "pâté-en-croute",
      "description": "Мясной пирог из гуся, фермерского петуха, говяжьей вырезки и костного мозга (лионская кухня)",
      "price": "980",
      "calories": "~380 ккал",
      "time": "2.5 ч",
      "origin": "Франция (Лион)",
      "history": "Лионская классика. Подается охлажденным, нарезается тонкими слайсами.",
      "facts": "• Тесто поднимается в 7 слоев\n• Фарш из гусиного мяса и петуха\n• Костный мозг даёт жирность",
      "wine": "Божоле Нуво, Пино Нуар",
      "image": "https://totgoose.github.io/pâté-en-croute.jpg",
      "allergens": "Глютен, Яйца, Молочные",
      "method": "Выпечка в тесте",
      "url": "dishes/pâté-en-croute.html"
    },
    {
      "name": "Говяжий ростбиф",
      "slug": "govyazhiy-rostbif",
      "description": "Слайсы вырезки на низкой температуре с печеным чесноком, вялеными томатами, горчичным соусом на кремовом сыре",
      "price": "980",
      "calories": "~210 ккал",
      "time": "1.5 ч",
      "origin": "Великобритания",
      "history": "Британское воскресное блюдо. Готовится при 55-60°C для розовой середины.",
      "facts": "• Вяленые томаты дают умами\n• Печеный чеснок сладкий\n• Горчичный соус на креме балансирует",
      "wine": "Мальбек, Шираз",
      "image": "https://totgoose.github.io/govyazhiy-rostbif.jpg",
      "allergens": "Молочные, Горчица",
      "method": "Су-вид/Запекание",
      "url": "dishes/govyazhiy-rostbif.html"
    }
  ]
};